version: '3.8'

services:
  nestjs:
    build: ./services/nestjs
    container_name: nestjs
    depends_on:
      - mongodb

  angular:
    build:  ./services/angular
    container_name: angular

  mongodb:
    image: mongo:4.4
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassrootword
    volumes:
      - ./services/mongodb/cfg/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - mongo_data:/data/db

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - '8084:8084'
    volumes:
      - ./services/nginx/cfg/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - angular
      - nestjs
      - mongodb

volumes:
  mongo_data: