version: '3.8'

services:
  nestjs:
    build: ./services/nestjs
    container_name: nestjs

  angular:
    build: ./services/angular
    container_name: angular

  mongodb:
    image: mongo:4.4
    container_name: mongodb
    #    environment:
    #      MONGO_INITDB_ROOT_USERNAME: root
    #      MONGO_INITDB_ROOT_PASSWORD: example

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - '8084:8084'
    volumes:
      - ./services/nginx/nginx.conf:/etc/nginx/nginx.conf