version: '3.8'

services:
  nestjs:
    build:
      context: ./services/nestjs
      dockerfile: dev.Dockerfile
    container_name: nestjs
    volumes:
      - ./services/nestjs/src/src:/app/src

  angular:
    build:
      context: ./services/angular
      dockerfile: dev.Dockerfile
    container_name: angular
    volumes:
      - ./services/angular/src/src:/app/src

  mongodb:
    image: mongo:4.4
    container_name: mongodb
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - '27017:27017'

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - '8084:8084'
    volumes:
      - ./services/nginx/nginx.conf:/etc/nginx/nginx.conf